Repository andoriyaprashant/OpSo, pull requests merged in 2024-06, with the labels that each got.

#175 codeql workflow added
  .github/workflows/codeql.yml
Labels: enhancement, gssoc, level3

#177 splash screen added
  android/app/src/main/res/drawable/launch_background.xml
  assets/splash screen.png
  lib/main.dart
  lib/splash_screen.dart
  pubspec.yaml
Labels: enhancement, gssoc, level2

#185 UI Improved for Linux Foundation Screen
  .gradle/8.0.2/checksums/checksums.lock
  .gradle/8.0.2/fileChanges/last-build.bin
  .gradle/8.0.2/fileHashes/fileHashes.lock
  .gradle/8.0.2/gc.properties
  .gradle/8.1.1/checksums/checksums.lock
  .gradle/8.1.1/checksums/md5-checksums.bin
  .gradle/8.1.1/checksums/sha1-checksums.bin
  .gradle/8.1.1/dependencies-accessors/dependencies-accessors.lock
  .gradle/8.1.1/dependencies-accessors/gc.properties
  .gradle/8.1.1/executionHistory/executionHistory.lock
  .gradle/8.1.1/fileChanges/last-build.bin
  .gradle/8.1.1/fileHashes/fileHashes.lock
  .gradle/8.1.1/gc.properties
  .gradle/buildOutputCleanup/buildOutputCleanup.lock
  .gradle/buildOutputCleanup/cache.properties
  lib/programs screen/linux_foundation.dart
  lib/widgets/linux_foundation_widget.dart
  local.properties
Labels: gssoc, level2, UI

#195 Implemented FAQs Page in the Menu.
  lib/home_page.dart
  lib/widgets/faq.dart
Labels: gssoc, level2

#202 Fixed app crash when notification permission is denied, issue #201
  .gradle/8.1.1/checksums/checksums.lock
  .gradle/8.1.1/dependencies-accessors/dependencies-accessors.lock
  .gradle/8.1.1/dependencies-accessors/gc.properties
  .gradle/8.1.1/executionHistory/executionHistory.lock
  .gradle/8.1.1/fileChanges/last-build.bin
  .gradle/8.1.1/fileHashes/fileHashes.lock
  .gradle/8.1.1/gc.properties
  .gradle/buildOutputCleanup/buildOutputCleanup.lock
  .gradle/buildOutputCleanup/cache.properties
  .gradle/buildOutputCleanup/outputFiles.bin
  lib/home_page.dart
  lib/main.dart
  lib/services/notificationService.dart
  pubspec.lock
Labels: gssoc, level2

#210 Added License
  LICENSE
  README.md
Labels: gssoc, level1

#204 Implemented All Info Pages for the Respective Programs.
  assets/coding_ninja_swag.png
  assets/github_swag.png
  assets/participation_certificate.png
  assets/xyz_domain.png
  lib/programs screen/girl_script.dart
  lib/programs screen/google_season_of_docs_screen.dart
  lib/programs screen/google_summer_of_code_screen.dart
  lib/programs screen/linux_foundation.dart
  lib/programs screen/social_winter_of_code.dart
  lib/programs screen/summer_of_bitcoin.dart
  lib/programs_info_pages/gsoc_info.dart
  lib/programs_info_pages/gsod_info.dart
  lib/programs_info_pages/gssoc_info.dart
  lib/programs_info_pages/linux_info.dart
  lib/programs_info_pages/sob_info.dart
  lib/programs_info_pages/swoc_info.dart
  pubspec.yaml
Labels: gssoc, level3

#217 Added projects for open summer of code
  assets/projects/osc/osc2021.json
  assets/projects/osc/osc2022.json
Labels: gssoc, level2

#219 Added Projects for Season of KDE
  assets/projects/sokde/sokde2022.json
  assets/projects/sokde/sokde2023.json
  assets/projects/sokde/sokde2024.json
Labels: gssoc, level2

#218 Added a clean UI page for Open Summer of Code
  assets/open_summer_of_code.png
  assets/projects/osoc/osoc2021.json
  assets/projects/osoc/osoc2022.json
  lib/home_page.dart
  lib/main.dart
  lib/modals/osoc_modal.dart
  lib/programs screen/open_summer_of_code.dart
  lib/widgets/osoc_widget.dart
  pubspec.yaml
Labels: gssoc, level2

#221 Implemented MLH Page
  .gradle/8.0.2/checksums/checksums.lock
  .gradle/8.0.2/fileChanges/last-build.bin
  .gradle/8.0.2/fileHashes/fileHashes.lock
  .gradle/8.0.2/gc.properties
  lib/programs screen/major_league_hacking_fellowship.dart
  pubspec.lock
Labels: gssoc, level3

#223 Implemented UI Page for Season of KDE
  assets/projects/sokde/sokde2022.json
  assets/projects/sokde/sokde2023.json
  assets/projects/sokde/sokde2024.json
  assets/sokde.png
  lib/home_page.dart
  lib/main.dart
  lib/modals/sokde_project_modal.dart
  lib/opso_timeline.dart
  lib/programs screen/season_of_kde.dart
  lib/programs_info_pages/sokde_info.dart
  lib/widgets/small_year_button.dart
  lib/widgets/sokde_project_widget.dart
  pubspec.yaml
Labels: gssoc, level3

#229 Fixed theme toggling bug
  .gradle/8.0.2/checksums/checksums.lock
  .gradle/8.0.2/fileHashes/fileHashes.lock
  lib/home_page.dart
  lib/main.dart
Labels: gssoc, level1

#230 Implemented the Info Page for OSoC and Update the Timeline
  lib/opso_timeline.dart
  lib/programs screen/open_summer_of_code.dart
  lib/programs_info_pages/osoc_info.dart
Labels: gssoc, level2

#203 Implemented chatbot feature for open source queries using Gemini
  lib/ChatBotPage.dart
  lib/home_page.dart
  pubspec.lock
  pubspec.yaml
Labels: gssoc, level2

#246 Added Projects for Outreachy
  assets/projects/outreachy/outreachy2021.json
  assets/projects/outreachy/outreachy2022.json
  assets/projects/outreachy/outreachy2023.json
  assets/projects/outreachy/outreachy2024.json
Labels: gssoc, level3

#245 Fixed bug in year button 2019 and 2020 of GSoD
  .gradle/7.5.1/checksums/checksums.lock
  .gradle/7.5.1/dependencies-accessors/dependencies-accessors.lock
  .gradle/7.5.1/dependencies-accessors/gc.properties
  .gradle/7.5.1/executionHistory/executionHistory.bin
  .gradle/7.5.1/executionHistory/executionHistory.lock
  .gradle/7.5.1/fileChanges/last-build.bin
  .gradle/7.5.1/fileHashes/fileHashes.bin
  .gradle/7.5.1/fileHashes/fileHashes.lock
  .gradle/7.5.1/gc.properties
  lib/modals/gsod/gsod_modal_old.dart
  lib/programs screen/google_season_of_docs_screen.dart
  lib/widgets/gsod/gsod_project_widget_old.dart
  pubspec.lock
Labels: gssoc, level2
