Repository andoriyaprashant/OpSo, pull requests merged in 2024-07, with the labels that each got.

#238 Reduced the Loading Time
  assets/projects/gsod/gsod2019.json
  assets/projects/gsod/gsod2020.json
  lib/modals/GSoC/Gsoc.dart
  lib/programs screen/google_summer_of_code_screen.dart
  lib/services/ApiService.dart
  lib/widgets/gsoc/GsocProjectWidget.dart
Labels: bug, level3

#252 Season of kde screen Fixed
  lib/programs screen/season_of_kde.dart
Labels: bug, gssoc, level2

#253 girlscript screen ListView issue solved
  lib/programs screen/girl_script.dart
Labels: gssoc, level2

#257 Splash Screen fixed
  lib/splash_screen.dart
Labels: gssoc, level2

#256 Hacktoberfest Screen Added
  assets/hacktoberfest.png
  lib/home_page.dart
  lib/main.dart
  lib/programs screen/hacktoberfest_screen.dart
  pubspec.lock
  pubspec.yaml
Labels: gssoc, level3

#258 Redox OS Projects Added
  assets/projects/redox/redox.json
Labels: gssoc, level2

#261 Implemented UI Page for Redox OS Summer of Code
  assets/redox.png
  lib/home_page.dart
  lib/main.dart
  lib/modals/rsoc_project_modal.dart
  lib/opso_timeline.dart
  lib/programs screen/redox.dart
  lib/programs_info_pages/rsoc_info.dart
  lib/widgets/rsoc_project_widget.dart
  pubspec.lock
  pubspec.yaml
Labels: gssoc, level3

#283 Removed the unnecessary asterisk
  lib/ChatBotPage.dart
Labels: bug, gssoc, level2

#284 Timeline Fixed
  lib/opso_timeline.dart
Labels: gssoc, level1

#285 redox screen fixed
  lib/programs screen/redox.dart
Labels: gssoc, level1

#286 Summer of bitcoin screen fixed
  lib/programs screen/summer_of_bitcoin.dart
Labels: gssoc, level3

#288 Github Campus Expert Screen Added
  assets/git_campus_logo.png
  lib/home_page.dart
  lib/main.dart
  lib/programs screen/github_campus.dart
  pubspec.yaml
Labels: gssoc, level3
