Repository andoriyaprashant/OpSo, pull requests merged in 2024-05, with the labels that each got.

#36 Created LEARN.md
  LEARN.md
Labels: gssoc, level1

#54 fixed Widget Test Error
  test/widget_test.dart
Labels: gssoc, level1

#52 About Page
  ios/Podfile
  lib/bar.dart
  lib/programs screen/girl_script.dart
  macos/Podfile
Labels: enhancement, gssoc, level1

#62 Added JSON files containing list of project from GSOD from year 2019 - 2023
  assets/projects/gsod/gsod2019.json
  assets/projects/gsod/gsod2020.json
  assets/projects/gsod/gsod2021.json
  assets/projects/gsod/gsod2022.json
  assets/projects/gsod/gsod2023.json
Labels: enhancement, gssoc, level3

#64 Added CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation, gssoc, level1

#71 GSOD page created issue #63
  .gradle/8.1.1/checksums/checksums.lock
  .gradle/8.1.1/checksums/md5-checksums.bin
  .gradle/8.1.1/checksums/sha1-checksums.bin
  lib/modals/gsod/gsod_modal_new.dart
  lib/modals/gsod/gsod_modal_old.dart
  lib/programs screen/google_season_of_docs_screen.dart
  lib/widgets/gsod/gsod_project_widget_new.dart
  lib/widgets/gsod/gsod_project_widget_old.dart
  lib/widgets/gssoc_project_widget.dart
  pubspec.yaml
Labels: enhancement, gssoc, level2

#67 Push Notification Implemented
  android/app/build.gradle
  android/app/src/main/AndroidManifest.xml
  lib/home_page.dart
  lib/main.dart
  lib/services/notificationService.dart
  linux/flutter/generated_plugin_registrant.cc
  linux/flutter/generated_plugins.cmake
  macos/Flutter/GeneratedPluginRegistrant.swift
  pubspec.lock
  pubspec.yaml
  windows/flutter/generated_plugin_registrant.cc
  windows/flutter/generated_plugins.cmake
Labels: enhancement, gssoc, level2

#69 Fixed Bugs on girl_script.dart
  lib/programs screen/girl_script.dart
Labels: bug, gssoc, level1

#77 circular loadin indicator fixed #76
  lib/programs screen/girl_script.dart
  lib/programs screen/google_season_of_docs_screen.dart
Labels: good first issue, gssoc, level1

#74 Update: Improved Code Quality and Added Search Functionality
  lib/bar.dart
Labels: gssoc, level1

#90 Implemented Sliding Navbar as suggested
  lib/home_page.dart
Labels: gssoc, level2

#93 Create pull_request_template.md
  .github/pull_request_template.md
Labels: documentation, gssoc, level1

#102 Summer of Bitcoins page added
  assets/projects/sob/sob2021.json
  assets/projects/sob/sob2022.json
  assets/projects/sob/sob2023.json
  lib/home_page.dart
  lib/modals/sob_project_modal.dart
  lib/programs screen/summer_of_bitcoin.dart
  lib/widgets/sob_project_widget.dart
  pubspec.yaml
Labels: gssoc, level2

#107 changed-logo
  lib/about.dart
Labels: enhancement, gssoc, level1

#87 Fixed the UI of GSoD screen
  lib/programs screen/google_season_of_docs_screen.dart
  lib/widgets/gsod/gsod_project_widget_new.dart
  lib/widgets/gsod/gsod_project_widget_old.dart
Labels: good first issue, gssoc, level1

#114 Implemented the GSoC Page
  lib/main.dart
  lib/modals/GSoC/Gsoc.dart
  lib/programs screen/google_summer_of_code_screen.dart
  lib/services/ApiService.dart
  lib/widgets/gsoc/GsocProjectWidget.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement, gssoc, level3

#118 Dark Mode feature added
  lib/home_page.dart
  lib/main.dart
  lib/programs screen/girl_script.dart
  lib/programs screen/google_season_of_docs_screen.dart
  lib/programs screen/google_summer_of_code_screen.dart
  lib/programs screen/summer_of_bitcoin.dart
  lib/widgets/gsoc/GsocProjectWidget.dart
  lib/widgets/gsod/gsod_project_widget_new.dart
  lib/widgets/gsod/gsod_project_widget_old.dart
  lib/widgets/gssoc_project_widget.dart
  pubspec.yaml
Labels: enhancement, gssoc, level2

#126 Linux Foundation page added
  lib/landing_page.dart
  lib/modals/linux_foundation_modal.dart
  lib/programs screen/google_season_of_docs_screen.dart
  lib/programs screen/linux_foundation.dart
  lib/widgets/linux_foundation_widget.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement, gssoc, level2

#127 Implemented Project Features for GSoC Page
  lib/programs screen/google_summer_of_code_screen.dart
  lib/widgets/gsoc/GsocProjectWidget.dart
Labels: enhancement, gssoc, level2

#140 Implemented UI Enhancement in Summer of Bitcoin Page.
  lib/widgets/sob_project_widget.dart
Labels: enhancement, gssoc, level2

#144 Improved UI for Google Season of Docs Screen
  lib/widgets/gsod/gsod_project_widget_new.dart
  lib/widgets/gsod/gsod_project_widget_old.dart
Labels: gssoc, level2, UI

#146 "Successfully Implemented the Notifications for the TimeLine Feature"
  lib/opso_timeline.dart
  lib/services/notificationService.dart
Labels: enhancement, gssoc, level3

#152 Added the feature to auto comment on pr merged
  .github/workflows/auto-comment-on-pr-merge.yml
Labels: documentation, good first issue, gssoc, level1

#151 Flutter and Dart ci added
  .github/workflows/flutter-ci.yml
Labels: gssoc, level2

#153 Update home_page.dart
  lib/home_page.dart
Labels: gssoc, level1

#154 Update README.md
  README.md
Labels: gssoc, level1

#156 Dependabot Added
  .github/workflows/dependabot.yaml
Labels: gssoc, level1

#157 Added the feature to auto comment on a new issue creation
  .github/workflows/auto-comment-on-issue.yml
Labels: gssoc, level1

#159 Added the feature to auto comment on pull request being raised
  .github/workflows/auto-comment-pr-raise.yml
Labels: gssoc, level1

#158 Implemented Swipe Down Reload Feature for each Program Screen
  lib/programs screen/girl_script.dart
  lib/programs screen/google_season_of_docs_screen.dart
  lib/programs screen/google_summer_of_code_screen.dart
  lib/programs screen/linux_foundation.dart
  lib/programs screen/major_league_hacking_fellowship.dart
  lib/programs screen/outreachy.dart
  lib/programs screen/summer_of_bitcoin.dart
Labels: enhancement, gssoc, level2

#162 added workflow as per issue #149
  .github/workflows/autocomment-iss-close.yml
Labels: gssoc, level1

#167 Bookmark feature added for the Summer of Bitcoin and the GSOC screen
  .gradle/buildOutputCleanup/buildOutputCleanup.lock
  .gradle/buildOutputCleanup/cache.properties
  lib/programs screen/google_summer_of_code_screen.dart
  lib/programs screen/summer_of_bitcoin.dart
  local.properties
Labels: gssoc, level2
