Repository andoriyaprashant/OpSo, pull requests merged in 2024-10, with the labels that each got.

#327 Bookmark Navigation Fixed
  lib/main.dart
  lib/programs screen/google_summer_of_code_screen.dart
Labels: level1, hacktoberfest-accepted, gssoc-ext

#337 empty state added in search
  assets/no-results.png
  lib/home_page.dart
  pubspec.yaml
Labels: level1, hacktoberfest-accepted, gssoc-ext

#349 bookmark updated successfully
  lib/widgets/book_mark_screen.dart
Labels: good first issue, level1, hacktoberfest-accepted, gssoc-ext

#363 Added all for filter in GSoC
  lib/programs screen/google_summer_of_code_screen.dart
Labels: level1, hacktoberfest-accepted, hacktoberfest, gssoc-ext

#348 back arrow and title updated
  lib/ChatBotPage.dart
  lib/about.dart
  lib/bar.dart
  lib/home_page.dart
  lib/learning_path.dart
  lib/opso_timeline.dart
  lib/programs screen/fossasia.dart
  lib/programs screen/girl_script.dart
  lib/programs screen/github_campus.dart
  lib/programs screen/google_season_of_docs_screen.dart
  lib/programs screen/google_summer_of_code_screen.dart
  lib/programs screen/hacktoberfest_screen.dart
  lib/programs screen/hyperledger.dart
  lib/programs screen/linux_foundation.dart
  lib/programs screen/major_league_hacking_fellowship.dart
  lib/programs screen/open_summer_of_code.dart
  lib/programs screen/outreachy.dart
  lib/programs screen/redox.dart
  lib/programs screen/season_of_kde.dart
  lib/programs screen/social_winter_of_code.dart
  lib/programs screen/summer_of_bitcoin.dart
  lib/widgets/book_mark_screen.dart
  lib/widgets/faq.dart
Labels: Stale

#387 Create project structure
  Project_Structure.md
Labels: documentation, level1, hacktoberfest, gssoc-ext
