Repository andoriyaprashant/OpSo, pull requests merged in 2024-08, with the labels that each got.

#294 GitHub Campus Expert Added to the OpSo Timeline.
  lib/opso_timeline.dart
Labels: gssoc, level1

#295 FOSSASIA Codeheat projects added
  assets/projects/fossasia/fossasia2016.json
  assets/projects/fossasia/fossasia2017.json
  assets/projects/fossasia/fossasia2018.json
  assets/projects/fossasia/fossasia2019.json
  assets/projects/fossasia/fossasia2020.json
Labels: gssoc, level3

#297 GitHub Campus Expert Text Color Fixed
  lib/programs screen/github_campus.dart
Labels: gssoc, level1

#298 FOSSASIA Codeheat UI Page Added
  assets/fossasia.png
  lib/home_page.dart
  lib/main.dart
  lib/modals/fossasia_project_modal.dart
  lib/opso_timeline.dart
  lib/programs screen/fossasia.dart
  lib/programs_info_pages/fossasia_info.dart
  lib/widgets/fossaisa_project_widget.dart
  pubspec.yaml
Labels: enhancement, gssoc, level3

#299 FAQs Added
  lib/widgets/faq.dart
Labels: gssoc, level3

#301 Bookmark Added (Google summer of code)
  lib/programs screen/google_summer_of_code_screen.dart
Labels: gssoc, level2

#303 Auto assign feature added
  .github/workflows/issue-assign.yml
Labels: gssoc, level3

#304 Projects for WOC added
  assets/projects/woc/woc.json
Labels: gssoc, level3

#308 Learning Path Added
  lib/home_page.dart
  lib/learning_path.dart
Labels: gssoc, level2

#312 Update README.md
  README.md
Labels: gssoc, level2

#307 GSoC Bugs Fixed
  lib/modals/GSoC/Gsoc.dart
  lib/programs screen/google_summer_of_code_screen.dart
  lib/widgets/gsoc/GsocProjectWidget.dart
Labels: gssoc, level3
